language: java

jdk:
  - oraclejdk7
  - openjdk7
  - openjdk6

branches:
  except: webanalytics

before_install:
- git checkout master
- git merge ${TRAVIS_BRANCH}
- git branch -v
- git remote show origin

script: "mvn test"
