language: java

jdk:
  - oraclejdk7
  - openjdk7
  - openjdk6

branches:
  except: webanalytics

# Merge the current branch into master before we test
before_install:
- git config --global user.email "travis@example.net"
- git config --global user.name "travis"
- git checkout master
- git branch -v
- git merge $TRAVIS_BRANCH
- git branch -v
- git remote show origin
- echo $TRAVIS_COMMIT_MESSAGE

# Execute everything in the build lifecycle before the test build phase
# We do this to make the output under the actual script show only output related to the test build phase
install: /bin/true

before_script:
- mvn process-resources
- mvn compile

# Only execute till build phase test
script: "mvn test"


# Deploy artifact to staging
after_success:
# Only deploy when on master branch
- if [[ "$TRAVIS_BRANCH" == "master" ]]; then echo "Deploying master to staging."; fi
