language: java
jdk:
- openjdk7
branches:
  except: webanalytics
env:
  global:
  - secure: CPaQpXrUdqpKF5JoOYQOb0OsbIwTuBYEyKABbTqbfMpdupQptNhmtEFI2UWM+1QTLv9R7WweBHPF1N/LHPs9ylBEdffedLHbeDtac5q8XXS7Rw9Mr/eb02JrkAJNqVgwDAwb/1vHCwTbG8ma+CJ0uGn7QjAaVjo2GKRzlhVXvpc=
  - secure: DY/YZ/7jcSH1ZWe+4KY0435Nz2X6zGO1INXw738P+AZAcACZeyWtMq5U4X1T3tCoVHwHuIGV29caM1kwOc1QJgXi+ncKjRg6Nxg8f7+kug4kcskkDYjgAg8uwHbi9f0kE0KeHYe3Ig/8T/56lZo5xJKU41g8zXB73ebyCwpwPCM=
  - secure: QQR5JZw0pE37KD0YRC/hYmDGQz1MrN4otLlD0gqTQBJvYisNpQvTYm6/Z1QdyjqmAKrtCUD0gW6TusVI9omlJ2sGGMEI2Dd5Zpwks3k+uS3o/Y+/ptHpwZfkfgsmJ2nODOvYWNY7Sf/9qrG3iLj11sqeSDPpQ4yFB3SLfjzTQPY=
  - secure: CK/NQkIpu4kkrS7fRNGGeoUOkjqsfnRi87v+afNNoPSLSksQ1RWBzPCiAmLlrOU7MI3dc5ooNWcOs3/ypY4ZdJwT8MMHlP1zbAhvAtDWDmniROEvV8HVivCQPzz8ePFrJOywfc/6C6KHZg7Jh1UirFCSNWs4p5vq0qGl/9pQPSg=
  - secure: NlB12+QwbjGFpTVSMVexy7EmaOuIrOOnSR73Z/d6k9k1UjRBfVG7kViGs2l/jnVdbAYNOcnFN706WnpTDD1UtyA+bDtIpATzNB0LeQHIUozmPoSnXJicvZEDnz/8Fnh7epSyEYVl3kHfIHPNu2MotBd6npnkWFsLxikATDj4a88=
  - secure: MF9zD9sbPfhIGvOiUjzC9h33chcawK3N2rJROkCWYBWY5j8awlkAAUZk38aveuLB4RVg/pcC3mI40o7wv+ZfHtHFi4YX9JgshjbtlO/f4dEWLv1XwnCPmUKNgrfCM14hyM0It4kp0/q+wus+aEfQrYJ5mD+TnP1nsxQtZwddQWE=

before_install:
- export COMMIT_MESSAGE=`git log -1 --format=%s%n%b`
- echo $COMMIT_MESSAGE
- if echo "$COMMIT_MESSAGE" | grep -i -q "\[merge]"; then export MERGE_TO_MASTER="true";
  fi
- echo $MERGE_TO_MASTER
- git config --global user.email "travis@example.net"
- git config --global user.name "travis"
- git checkout master
- git branch -v
- git merge --no-ff $TRAVIS_BRANCH
- git branch -v
- git remote show origin
install: mvn -v
before_script:
- mvn process-resources
- mvn compile
script: mvn test
after_success:
- if [[ "$TRAVIS_BRANCH" != "master" ]] && [[ "$MERGE_TO_MASTER" == "true" ]]; then
  echo "Merging $TRAVIS_BRANCH to master" && git push https://$GITHUB_TOKEN:x-oauth-basic@github.com/${TRAVIS_REPO_SLUG}.git
  master; fi
- if [[ "$TRAVIS_BRANCH" == "master" ]]; then echo "Deploying master to staging."
  && mvn package
  && sudo apt-get install sshpass
  && curl "$TOMCAT_USER:$TOMCAT_PASSWORD@$TOMCAT_HOST:8080/manager/text/undeploy?path=/petclinic"
  && wait ${!}
  && sshpass -p $TOMCAT_HOST_PASSWORD ssh -oStrictHostKeyChecking=no $TOMCAT_HOST_USER@$TOMCAT_HOST "sudo /etc/init.d/tomcat7 restart"
  && wait ${!}
  && curl -T "target/petclinic.war" "$TOMCAT_USER:$TOMCAT_PASSWORD@$TOMCAT_HOST:8080/manager/text/deploy?path=/petclinic";
  fi
